version: "3.2"
services:
  docs:
    image: ghcr.io/codex-team/codex.docs:stage-17857c8-1667816216 # need to be changed after release
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./db:/usr/src/app/db
      - ./docs-config.local.yaml:/usr/src/app/docs-config.yaml
